Homepage had to be remade using new design, so this commit issues tha…
hashlabs/hashlabs.github.io pull request #20
Opened 2017-03-07 21:57 UTC by TheMightyPenguin

# Context
Homepage had to be remade using new design, so this commit issues that by:

- Added lead section.
- Added brands section.
- Added what we do section.
- Added techonologies/tools section.
- Added how section.
- Added CAT (call to action) section.
- Added FAW section.

All these sections have their own styles, and were done as separate
components, so they are easy to modify, remove or reorder.

## Links
[Desktop design](https://app.zeplin.io/project.html#pid=5888b73ba8de3a354ef67567&sid=588f6811cb4fd20443ab9447)
[Mobile design](https://app.zeplin.io/project.html#pid=5888b73ba8de3a354ef67567&sid=58b86d91c50cf643a18ef7b2)

## Media

2017-03-07 22:20 UTC, orlando commented
@TheMightyPenguin can you post a screenshot please?

2017-03-08 15:51 UTC, duranmla commented
@TheMightyPenguin in this case I will feel even more comfortable to approve if you share me a ngrok link with your localhost just to be able to play again with the site. (keep the gif there as reference too)

2017-03-08 16:06 UTC, duranmla requested changes
The bottom line is to keep in mind to make the code clear, remember that you are writing code for humans, always aim to make your code as readable as possible.

But overall good work mate, today is the last day for this, so let's make it happen.

2017-03-08 16:06 UTC, duranmla commented on Gemfile
> +gem 'jekyll-autoprefixer'
Everytime we add things like this one I want to see a link within the PR context and an explanation of why we needed so we all will be clear of why we have introduced a new dependency.

2017-03-08 16:06 UTC, duranmla commented on _includes/footer-scripts.html
> +<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/flexibility/2.0.1/flexibility.js"></script>
Same as before, why we need this one?

2017-03-08 16:06 UTC, duranmla commented on _includes/section-cat.html
> +<div class="container-fluid section-cat-container">
maybe we want to change to CTA instead CAT right? `Call To Action` so let's update the class names that contains "cat"

2017-03-08 16:06 UTC, duranmla commented on _sass/_components--brands.scss
> +$size--brand-width:                   100% / $size--brand-quantity - 1;
let's use parenthesis on this type of operations like: `100% / ($size--brand-quantity - 1)`

2017-03-08 16:06 UTC, duranmla commented on _sass/_components--brands.scss
> +$size--brand-width-tablet:            100% / 2 - 1;
what is `2` and `1` and why `(2 - 1)` I will rather prefer variables for those than the percentages for the images width.

2017-03-08 16:06 UTC, duranmla commented on _sass/_components--brands.scss
> +$size--brand-width-small:             100%;
brand-image? or what is the difference between brand and brand-image? there is more variables below that say `brand-image`

2017-03-08 16:06 UTC, duranmla commented on _sass/_components--footer.scss
> +// showing this tablets and below.
"...in order to keep the aligned on mobile devices" and yes awesome comment

2017-03-08 16:06 UTC, duranmla commented on _sass/_components--footer.scss
> +    width: 44px;
so this should be a variable on the variables file don't you think? like "size--brand-logo"

2017-03-08 16:06 UTC, duranmla commented on _sass/_components--technologies.scss
> +$size--tech-width-large:     100% / 6 - 1; // all techs on a single row
that comment is great but why we use `-1`? I want to minimize my effort to understand the code while I am reading, we need to make it as clear and obvious as possible

2017-03-08 16:06 UTC, duranmla commented on _sass/_components--technologies.scss
> +$size--tech-width-large:     100% / 6 - 1; // all techs on a single row
Add this type of comment on the feedback above that has the same approach

2017-03-08 16:06 UTC, duranmla commented on _sass/_settings--fonts.scss
> +  @import url('https://fonts.googleapis.com/css?family=Montserrat:300,400,500,700');
damn do we actually need all of that?

2017-03-09 20:45 UTC, duranmla approved these changes

2017-03-09 20:45 UTC, duranmla commented
@TheMightyPenguin LGTM

2017-03-09 20:46 UTC, merged