Implemented home page
hashlabs/hashlabs.github.io pull request #97
Opened 2017-07-31 21:16 UTC by Carlows

# Context

This PR implements the home page.

It also fixes the layout of the footer in tablet devices.

## Media

### Mobile

![image](https://user-images.githubusercontent.com/4183514/28798218-d3fe0666-7611-11e7-9272-106ce4907b32.png)

![image](https://user-images.githubusercontent.com/4183514/28798225-db158b9a-7611-11e7-83dd-c36a639ad19d.png)

### Tablet

![image](https://user-images.githubusercontent.com/4183514/28798237-e4978a92-7611-11e7-874a-9287b731d7fb.png)

![image](https://user-images.githubusercontent.com/4183514/28798241-ea0e5fc8-7611-11e7-964c-e4a26de39288.png)

### Desktop

![image](https://user-images.githubusercontent.com/4183514/28798263-f4ae335e-7611-11e7-9eef-b75ab3d3d2d7.png)

![image](https://user-images.githubusercontent.com/4183514/28798271-fb2bae00-7611-11e7-8ac7-587fbaf36569.png)

### General

http://recordit.co/aj5r5LjG8o (too big for github 🙂)

2017-07-31 21:24 UTC, duranmla requested changes
Same as @TheMightyPenguin let's not use includes for snippets that belongs only to a certain page, besides, make sure the name of the settings jekyll file match the format.

2017-07-31 21:28 UTC, duranmla commented on _sass/_layouts--global.scss
> -      padding-top: $size--header-height;
@Carlows remember to add the padding top on services page

2017-07-31 21:31 UTC, TheMightyPenguin requested changes

2017-07-31 21:31 UTC, TheMightyPenguin commented on css/settings-jekyll.scss
> + * HOME Lead section
Below this section name,could you also put the name of the file where the class is defined? 
like

```
/**
 * Specific services sections
 * _sass/_components--service.scss
 */
```

2017-07-31 21:31 UTC, TheMightyPenguin commented on _includes/head.html
> +  <link rel="stylesheet" href="{{ "/css/settings-jekyll.css" | prepend: site.baseurl }}">
Could you include this after `main.css`?

2017-07-31 21:32 UTC, TheMightyPenguin commented on css/settings-jekyll.scss
> + * HOME Lead section
Also, this file should be named `settings--jekyll.scss`

2017-07-31 23:58 UTC, Carlows commented on _sass/_partials--services.scss
> +  padding-top: $size--header-height;
@TheMightyPenguin it's here

2017-08-01 00:02 UTC, TheMightyPenguin approved these changes
LGTM :+1:

2017-08-01 01:07 UTC, duranmla approved these changes

2017-08-01 01:10 UTC, merged